language: go

addons:
  apt:
    packages:
      - oracle-java8-set-default

go:
  - 1.6.4
  - 1.7.5

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  matrix:
    - ES_VERSION=1.7.5 ES_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.5.tar.gz
    - ES_VERSION=2.4.4 ES_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.4/elasticsearch-2.4.4.tar.gz
    - ES_VERSION=5.2.0 ES_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.0.tar.gz

before_script:
  - java -version
  - echo $JAVA_HOME
  - mkdir ${HOME}/elasticsearch
  - wget $ES_URL
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz -C ${HOME}/elasticsearch
  - "echo 'script.inline: true' >> ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/config/elasticsearch.yml"
  - ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - wget --retry-connrefused http://127.0.0.1:9200/ # Wait for ES to start up

install:
  - go get github.com/Masterminds/glide

script:
  - make test
